### PR TITLE
Added 1212 (Metric 3030) inductor footprint

### PR DESCRIPTION
**Pull request by SchrodingersGat**

### CODE REVIEW

**Comment by CarlPoirier** [comment]
Hi Oliver,

As per rule 6.5, silkscreen must not go over the pads. I suggest you take a look at how the SMD resistors and capacitors are done. Also, if the part has no polarity, there is no need to mark pin 1!

Besides that, it looks good!

**Comment by SchrodingersGat** [comment]
Done!

**Comment by CarlPoirier** [comment]
You didn't fix the NR4018!

**Comment by SchrodingersGat** [comment]
Check again! :p

**Comment by CarlPoirier** [comment]
Thanks for your great contribution!

**Pull request merged**
