### PR TITLE
Generated footprints for Wurth HCM inductors

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Footprints generated with python script:
https://github.com/SchrodingersGat/kicad-footprint-generator/blob/master/scripts/Inductors/we-hcm.py

**Datasheets**
http://katalog.we-online.com/pbs/datasheet/744302007.pdf
http://katalog.we-online.com/pbs/datasheet/744307012.pdf
http://katalog.we-online.com/pbs/datasheet/744303012.pdf
http://katalog.we-online.com/pbs/datasheet/744308015.pdf
http://katalog.we-online.com/pbs/datasheet/7443081010.pdf
http://katalog.we-online.com/pbs/datasheet/744306020.pdf
http://katalog.we-online.com/pbs/datasheet/744301025.pdf
http://katalog.we-online.com/pbs/datasheet/744304010.pdf
http://katalog.we-online.com/pbs/datasheet/744305022.pdf
http://katalog.we-online.com/pbs/datasheet/744309012.pdf

### CODE REVIEW

**Comment by pointhi** [comment]
you made some errors in the table:

https://github.com/SchrodingersGat/kicad-footprint-generator/blob/master/scripts/Inductors/we-hcm.py#L5

**Comment by SchrodingersGat** [comment]
Which one(s) is/are wrong? :)

**Comment by pointhi** [comment]
For example `1390`, `1240`,...

**Comment by SchrodingersGat** [comment]
You might have to be a little more specific, I can't spot the mistake(s)... :)

**Comment by pointhi** [comment]
``` python
[1390, 12.5, 13, 2.5, 10, 5]
```

should be at least (for the L-dimensions):

``` python
[1390, 14.0, 13, 2.5, 10, 5]
```

according to: http://katalog.we-online.de/en/pbs/WE-HCM?m=t&sq=hcm+1050&sp=http%3A%2F%2Fwww.we-online.com%2Fweb%2Fen%2Felectronic_components%2Fsearchpage_PBS.php%3Fsearch%3DHCM-1050

**Comment by SchrodingersGat** [comment]
The 'L' dimension refers only to the inductor body and not to the metal legs. The script uses the 12.5mm dimension as given here:

untitled

**Comment by pointhi** [comment]
ok, my fault. Thanks for your great contributions.

**Pull request merged**
