### PR TITLE
Add Würth SPC Inductors

### PR DESCRIPTION
**Pull request by pointhi**
source: http://katalog.we-online.com/en/pbs/WE-SPC
inductor_spc

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

rename `Würth` to `Wurth` ... like all other Würth footprints? Otherwise: OK

cu
JAN

**Comment by pointhi** [comment]
I think we should rename the other ones to `Würth`, because this would be the correct naming

**Comment by jkriege2** [comment]
Then maybe `Wuerth`? ... I think non-ASCII-symbols in filenames can still generate problems with encoding ...already our checkscripts cannot cope ... ;-)

cu
JAN

**Comment by pointhi** [comment]
hm, @CarlPoirier what do you say.

I used the official writing in https://github.com/KiCad/Shielding_Cabinets.pretty, so we would need to change it if we use this transcription

**Comment by jkriege2** [comment]
hi!

this repo has been deprecatd. Please resubmit you PR to the new SMD-inductors repo, using the naming standard used there:
https://github.com/KiCad/Inductors_SMD.pretty

Best,
JAN

**Comment by SchrodingersGat** [comment]
@pointhi  I am closing this PR as this should be moved to the other repository. Please make a new PR there if you still wish to contribute :) Thanks!

**Pull request closed without merging**
